config/routes.rb
Call::Application.routes.draw do
  resources :activities

  get "sched/sched"
  get "players/players_json"

  resources :players
  
  resources :avails 
  

  root :to => 'sched#sched'

  match ':controller(/:action(/:id))(.:format)', via: :all
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  attr_accessible :name
end

app/models/avail.rb
class Avail < ActiveRecord::Base
  # include EnumHandler
  
  attr_accessible :player_id, :day, :time
  belongs_to :player
  
  # define_enum :day, [:mon, :tue, :wed, :thu, :fri, :sat, :sun]
  
  # ==========
  # = Scopes =
  # ==========
  # scope :cast_members, -> { where(role: :cast) }
  # scope :crew_members, -> { where(role: :crew) }
  scope :cast_members, -> { where(role: 'cast') }
  scope :crew_members, -> { where(role: 'crew') }
  
  # =================
  # = Class Methods =
  # =================
  
  
end

app/models/player.rb
class Player < ActiveRecord::Base
  include EnumHandler
  
  attr_accessible :first_name, :last_name, :role, :note
  
  # define_enum :role, [:cast, :crew], :primary => true
  
  has_many :avails, :dependent => :destroy
  
  validates :first_name, :last_name, :role, :presence => true
  validates :first_name, :uniqueness => {:scope => :last_name, :message => "  :: A player with this first and last name exists."}
  
  def full_name
    "#{first_name} #{last_name}".capitalize_words
  end
  
  def set_avails(new_avails)
    # Get rid any existing avails for the player
    avails.each{|a| a.destroy}
    
    # Add the new ones for him
    new_avails = new_avails.map{|a| a.merge({:player_id => id})}
    new_avails.each{|a| Avail.create(a)}
  end

  def self.crew
    Player.where({role: 'crew'})
  end
  
  def self.cast
    Player.where({role: 'cast'})
  end 

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @activities }
    end
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
    @activity = Activity.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/new
  # GET /activities/new.json
  def new
    @activity = Activity.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/1/edit
  def edit
    @activity = Activity.find(params[:id])
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(params[:activity])

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render json: @activity, status: :created, location: @activity }
      else
        format.html { render action: "new" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /activities/1
  # PUT /activities/1.json
  def update
    @activity = Activity.find(params[:id])

    respond_to do |format|
      if @activity.update_attributes(params[:activity])
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to activities_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  
  def new
    render :template => "players/new"
  end
  
  
  def create
    normalize_params
    @player = Player.new params[:player]
    if @player.save
      @player.set_avails(JSON.parse params[:avails])
      redirect_to "/sched/sched"
    else
      @avails = JSON.parse params[:avails]
      new
    end
  end

  def edit
    @player ||= Player.find params[:id]
    @players = [ @player]
    render :template => "players/edit"
  end
  
  def update
    normalize_params
    @player = Player.find params[:id]
    if @player.update_attributes(params[:player].only(@player.attributes.keys))
      @player.set_avails(JSON.parse params[:avails])
      redirect_to "/sched/sched"
    else
      edit
    end
  end
  
  def destroy
    player = Player.find(params[:id]).destroy
    redirect_to "/sched/sched"
  end
  
  def players_json
    render :json => Player.all.sort{|a,b| a.first_name <=> b.first_name}.map{ |p| p.attributes.merge(:avails => p.avails.map{|a| a.attributes}) }
  end
  
  private
  
  def normalize_params
    params[:player][:first_name] &&= params[:player][:first_name].strip.capitalize_words
    params[:player][:last_name] &&= params[:player][:last_name].strip.capitalize_words
  end
  
end

app/controllers/sched_controller.rb
class SchedController < ApplicationController
  
  def sched
    @players = Player.all
    @cast_and_crew = {:crew => Player.crew.sort{|a,b| a.first_name <=> b.first_name}, :cast => Player.cast.sort{|a,b| a.first_name <=> b.first_name}}
  end
  
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def times
    t = []
    (10..17).each do |hr|
      ["00", "30"].each do |min|
        t.push (hr.to_s + min).to_i
      end
    end
    t
  end
  
  
  def display_time(time)
    Time.strptime(time.to_s, '%H%M').strftime('%l:%M %P')
  end
  
  def display_role(role)
    role.to_s.capitalize_words
  end
    
  def availability_on(day, time, availability)
    a = ""
    availability.each do |avail|
      avail = avail.symbolize_keys
      if day == avail[:day].to_sym && time.to_i == avail[:time].to_i
        a = "available"
        break
      end
    end
    return a
  end
  
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/sched_helper.rb
module SchedHelper
end

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<h1>Listing activities</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @activities.each do |activity| %>
  <tr>
    <td><%= activity.name %></td>
    <td><%= link_to 'Show', activity %></td>
    <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
    <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<h1>New activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @activity.name %>
</p>


<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Call</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/players/_player_availability.html.erb
<h3>Availability</h3>
<div style="padding-bottom:15px">Half hour time slots starting at given time. Click time slot to set availability.</div>
<div style="padding-bottom:10px">
  <span class="pseudo_link week_all" onclick="AvailabilityView.week_all()">Set All Available</span> &nbsp;&nbsp;
  <span class="pseudo_link week_none" onclick="AvailabilityView.week_none()">Set None Available</span>
</div>

<%= render :partial => '/shared/availability_table' %>

<div style="padding-top:25px">
  <span class="pseudo_button blue" onclick="PlayerController.post()">Submit</span>&nbsp; &nbsp; 
  <span class="pseudo_button grey" onclick="window.location = '/sched/sched'">Cancel</span>
</div>

app/views/players/_player_fieldset.html.erb
<div class="field_set">
  <%= f.error_messages %>
  <input id="player_availability" type="hidden" name="avails" ></input>
  
  <div class="inline_fields">
    <span class="label">First Name</span>
    <%= f.text_field :first_name, :class => :text, :size => :auto %>
 
    <span class="label" style="padding-left:20px">Last Name</span>
    <%= f.text_field :last_name, :class => :text, :size => :auto %>
 
    <%= f.label :role %>
    <span class="label" style="padding:0px">:</span>
    Cast <%= f.radio_button :role, :cast  %> &nbsp; &nbsp;
    Crew <%= f.radio_button :role, :crew  %>
  </div>
  <div class="label" style="padding: 15px 0px 10px">Special Unavailability</div>
  <%= f.text_area :note,  :class => :note_text_area %>
</div>

app/views/players/edit.html.erb
<script type="text/javascript" charset="utf-8">
  window.page_type = "edit"
  window.player_id = <%= @player.id %>
</script>

<h1>Edit Member</h1>
<%= form_for :player, :url => player_path(@player), :method => :put, :html => {:id => :new_player_form} do |f| %>
  <%= render :partial => 'player_fieldset', :locals => {:f => f} %>
<% end %>

<%= render :partial => 'player_availability' %>

app/views/players/new.html.erb
<h1>Add a Member</h1>
<%= form_for :player, :url => players_path, :html => {:id => :new_player_form} do |f| %>
  <%= render :partial => 'player_fieldset', :locals => {:f => f} %>
<% end %>

<%= render :partial => 'player_availability' %>

app/views/sched/sched.html.erb
<div class="sched">
  <% [:crew, :cast].each do |role| %>
    <div class="player_list">
      <h2><%= display_role role %> &nbsp; <span class="pseudo_link" onclick="SchedController.unselect_all()">unselect all</span> <span class="pseudo_button blue" onclick="window.location='/players/new'">Add <%= display_role role %> Members</span></h2>
      <% @cast_and_crew[role].each do |p| %>
        <div class="player_block id_<%= p.id %>" data-id="<%= p.id %>">
          <div class="player" onclick="SchedController.toggle(<%= p.id %>)"><%= p.full_name %></div>
          <div class="actions">
            <span class="pseudo_link" onclick="window.location='<%= edit_player_path p.id %>'; event.stopPropagation()">Edit</span> &nbsp; &nbsp; 
            <span class="pseudo_link" onclick="PlayerController.delete(<%= p.id %>); event.stopPropagation()">Delete</span>
          </div>
        </div>
      <% end %>  
    </div>
    <div class="clear"></div>
  <% end %>
  
  <h2>Special Availability</h2>
  <div class="special_avails">None</div>

  <h2>Weekly Availability</h2>
  <div style="padding-bottom:8px">Time slots represent the half hour starting at the indicated time.</div>
  <%= render :partial => '/shared/availability_table', :locals => {:context => :sched} %>
  
</div>

app/views/shared/_availability_table.html.erb
<% context = defined?(context) && context %>
<table id="availability_table" class="availabily" border="0" cellspacing="0" cellpadding="0" >
  <% days = [:mon, :tue, :wed, :thu, :fri, :sat, :sun] %>
    <% (days.length + 1).times do %>
      <col/>
    <% end %>
    <tr class="heading_row">
      <td>Time</td>
      <% days.each do |day| %>
        <td class="day_col_heading <%= day %>">
          <%= day.to_s.capitalize_words %>&nbsp; &nbsp;
          <% unless context == :sched %>
            <span class="pseudo_link day_all" onclick="AvailabilityView.day_all('<%= day %>')">All</span>&nbsp;
            <span class="pseudo_link day_none" onclick="AvailabilityView.day_none('<%= day %>')">None</span>
          <% end %>
        </td>
      <% end %>
    </tr>
    <% times.each do |time| %>
    <tr>
      <td><%= display_time(time) %></td>
      <% days.each do |day| %>
        <% available = @avails ? availability_on(day, time, @avails) : "available" %>
        <% logger.debug "day:#{day} time:#{time} avail:#{available}" %>
        <td <% unless context == :sched %>onclick="AvailabilityView.time_slot_toggle('<%= day %>','time_<%= time %>')"<% end %>
            data-day="<%= day %>" 
            data-time="<%= time %>" 
            class="<%= "valid #{available}" if [:mon, :tue, :wed, :thu, :fri].include?(day) && time >= 1500 || [:sat, :sun].include?(day) %>
                  time_slot <%= day %> <%= "time_#{time}" %>"
          ></td>
      <% end %>
    </tr>
    <% end %>
</table>